# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 921851ddb70f94f601c2c3929dfe0dc9f13ebbfa8f7fcb81ef6a9e90a48039cfc7fda589c21558296a492d4cca5c0a59b3cd2d568b2d49c6805a46d5d5333957

test:
  secret_key_base: 06716a200202d32a127253a32e041def38861a1fbb44f1cd8d47b27ae91ff0411aa8aee8dd539cb868dc8ca9629120a13648fcd04e8d0c913920cf963f43683d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
